### ISSUE TITLE
createDirectStream, multiple streams, atomicity and checkpoint failures

### ISSUE THREAD

**Issue by tzhang101** [koeninger/kafka-exactly-once#2]
Very good article on idempotent and transactional exactly once.
But I am hitting the following scenario where checkpoint itself is failing and cause partial writes.
Can you take a look and suggest?

I am using spark streaming 1.3.0 directStream. I am hitting the following Scenario and I would like your suggestion on how to design atomicity.
Here are pseudo codes to describe the flow and key points.

S1=createDirectStream(kafka) ==> I have OffsetRange associated with each RDD
S1.print ==> good

S2=S1.flatMap(some transformation) ==> It does not require checkpoint
S2.print ==> good

S3=S2.updateStateByKey(require checkpoint) ==> checkpoint failed due to hdfs issue for example
S3.print ==> nothing print out

S2.foreachRDD {
SaveToElasticSearch() ==> write to Elastic Search fine
}
S3.foreachRDD {
SaveToElasticSearch() ==> nothing written to Elastic Search
}

I was hoping the batch is atomic, i.e., as long as there are errors, offsets will not change and writes will not happen.
But 2 issues I have observed:
Kafka offsets kept moving on to next batch even there are dependent stream failed, e.g. S3.
Partial writes went to Elastic Search.

We would like to see
1) the offset stops if anything in this job failed and spark streaming will recover by itself from the right offsets.
2) Write all streams in one unit.

Any suggestions?

Tian

**Comment by koeninger** [comment]
I'm not 100% clear on what you're describing.

But unless you're atomically storing your offsets in elasticsearch in the same document as the corresponding results, you shouldn't expect atomic batches.  If you're relying on spark checkpoints for storing offsets, your output operation needs to be idempotent.

**Comment by tzhang101** [comment]
Thank you very much for responding, and let me provide more details. I am only store my results to ELastic Search and I have unique keys to ensure indempotent writes.

I am assuming my offsets are stored in checkpoints on hdfs, but the scenario is hdfs has issue, eg. it can't mkdir due to disk full. Then I assume the stream batch should hold offsets and not moving forward till the hdfs issue is resolved and checkpoint is good. But I confirmed that the batch moved on with new RDD's and new offsets.

**Comment by koeninger** [comment]
Even if that happens, can you not restart from the last successfully saved
checkpoint?

**Comment by tzhang101** [comment]
When that happens, I noticed the job just keep going on with S2 ok, but with S3 fail, and offset in S1 above keep increasing to next batch. I do not see where the checkpoint offset kick in?

**Comment by koeninger** [comment]
Sounds more related to expectations around checkpoint failure, as opposed
to anything specific to kafka.

I'd say make a small code example that demonstrates the issue, and bring it
up on the spark user mailing list or jira.

**Comment by tzhang101** [comment]
Ok, I will try to simplify my codes, but I may not be able to wait for a jira fix as I need to get it to work somehow. Another question, I am thinking to switch checkpoint from hdfs to s3, do you know how to do that? Do I just pass a path with s3://bucket/prefix? Thanks.

**Comment by koeninger** [comment]
Yeah, s3n://  urls will work for checkpoints.

You'll also need to set spark.hadoop.fs.s3n.awsAccessKeyId and
spark.hadoop.fs.s3n.awsSecretAccessKey.  To make sure those configurations
are available when restarting from checkpoint, you need to use the 3
argument form of getOrCreate like

```
  StreamingContext.getOrCreate(

    conf.get("whatevercheckpointpath"),

    () => yourSetupSparkStreaming(conf),

    SparkHadoopUtil.get.newConfiguration(conf)

  )
```

to make sure the right hadoop config is used

**Comment by tzhang101** [comment]
Here is what I did for switch checkpoint to S3, I am using spark 1.3 and running on mesos.

```
val checkpointDir = "checkpoint-ActRegExtractor"
val ssc = StreamingContext.getOrCreate(checkpointDir,
                                       () => getStreamingContext(SparkJobName, 
                                                                 batchDurationSec),
                                                                 classOf[ActRegKryoRegistrator],
                                                                 checkpointDir),
                                       getHadoopConfiguration)
```

My getHadoopConfiguration is defined as below

  def getHadoopConfiguration: Configuration = {
    val hadoopConf = new Configuration()
    hadoopConf.set("fs.defaultFS", "myBucke")
    hadoopConf.set("fs.s3.awsAccessKeyId", "myAccessKey")
    hadoopConf.set("fs.s3.awsSecretAccessKey", "mySecretKey")
    hadoopConf.set("fs.s3n.awsAccessKeyId", "myAccessKey")
    hadoopConf.set("fs.s3n.awsSecretAccessKey", "mySecretKey")
    hadoopConf
  }

I hit runtime error as below
Exception in thread "main" org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: S3 GET failed for '/%2Fuser%2Fmesos%2Fcheckpoint-ActRegExtractor' XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E59C4ED3F55B52F1</RequestId><HostId>7kXRKrG8aoo6O8gsaW8FH6TeydmtLAZL2yTAagKoA8MRUCRtdkeQxZ0wNfOwQpP6CKVm8pTB4hs=</HostId></Error>
    at org.apache.hadoop.fs.s3.Jets3tFileSystemStore.get(Jets3tFileSystemStore.java:168)
    at org.apache.hadoop.fs.s3.Jets3tFileSystemStore.retrieveINode(Jets3tFileSystemStore.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:164)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:83)
    at com.sun.proxy.$Proxy4.retrieveINode(Unknown Source)
    at org.apache.hadoop.fs.s3.S3FileSystem.getFileStatus(S3FileSystem.java:339)
    at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1332)
    at org.apache.spark.streaming.Checkpoint$.getCheckpointFiles(Checkpoint.scala:85)
    at org.apache.spark.streaming.CheckpointReader$.read(Checkpoint.scala:231)
    at org.apache.spark.streaming.StreamingContext$.getOrCreate(StreamingContext.scala:623)

What did I miss?
Is this work for 1.3?
Why my checkpointDir changed from checkpoint-ActRegExtractor to  '/%2Fuser%2Fmesos%2Fcheckpoint-ActRegExtractor' ?

Thanks.

Tian

**Comment by koeninger** [comment]
Did you set those credentials in your spark conf as well?

As far as the mesos path goes, I'm not sure why that is.

**Comment by tzhang101** [comment]
No, I only set credentials to hadoop Configuration as I looked the 1.3 spark code getOrCreate
it is using a brand new SparkConf each time.

def getOrCreate(
      checkpointPath: String,
      creatingFunc: () => StreamingContext,
      hadoopConf: Configuration = new Configuration(),
      createOnError: Boolean = false
    ): StreamingContext = {
    val checkpointOption = try {
      CheckpointReader.read(checkpointPath,  new SparkConf(), hadoopConf)
    } catch {
      case e: Exception =>
        if (createOnError) {
          None
        } else {
          throw e
        }
    }
    checkpointOption.map(new StreamingContext(null, _, null)).getOrElse(creatingFunc())
  }
